server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  config:
    activate:
      on-profile: dev
    import: application-secret.yml
  datasource:
    url: jdbc:postgresql://${database:localhost}:5432/db_stepbystep_website
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:060202}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
open:
  api:
    title: Api Document
    version: v1.0.0
    description: Api Service
    serverUrl: http://localhost:${server.port}
    serverName: Server Dev
