server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/db_stepbystep_website
    username: postgres
    password: "060202"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
open:
  api:
    title: Api Document
    version: v1.0.0
    description: Api Service
    serverUrl: http://localhost:${server.port}
    serverName: Server Dev
