package com.toilamdev.stepbystep.enums;

public enum PermissionName {
    //Module Course
    CREATE_COURSE, EDIT_COURSE, VIEW_COURSE, VIEW_COURSE_DETAIL, DELETE_COURSE, PUBLISH_COURSE, HIDE_COURSE,
    MANAGE_MY_COURSE,
    //Module Review
    CREATE_REVIEW, EDIT_REVIEW, DELETE_REVIEW, VIEW_REVIEW,
    //Module Post
    CREATE_POST, EDIT_POST, DELETE_POST, HIDE_POST, VIEW_POST, PUBLISH_POST, MANAGE_MY_POST,
    //Module Comment
    CREATE_COMMENT, EDIT_COMMENT, DELETE_COMMENT, HIDE_COMMENT,
    //Module Payment
    CREATE_PAYMENT, MANAGE_YOUR_PAYMENT
}
